apiVersion: v1
kind: Service
metadata:
  name: webstatus
  namespace: tedu
  labels:
    app: webstatus
spec:
  type: ClusterIP
  selector:
    app: webstatus
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstatus
  namespace: tedu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webstatus
  template:
    metadata:
      labels:
        app: webstatus
        tier: observability
    spec:
      containers:
        - name: webstatus
          image: webstatus:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          envFrom:
            - configMapRef:
                name: healthchecks-ui-config
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
