apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: tedu
type: Opaque
stringData:
  mssql-sa-password: "Passw0rd!"
  mysql-root-password: "Passw0rd!"
  postgres-user: "admin"
  postgres-password: "admin1234"
  mongo-root-username: "admin"
  mongo-root-password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: tedu
type: Opaque
stringData:
  username: "guest"
  password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: tedu
type: Opaque
stringData:
  username: "elastic"
  password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: tedu
type: Opaque
stringData:
  email: "admin@tedu.com.vn"
  password: "admin1234"
